project:
  type: website

website:
  title: "Taehwan Kim"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: projects.qmd
        text: Projects
      - href: notes.qmd
        text: Notes
      - href: teaching.qmd
        text: Teaching
      - href: ta.qmd
        text: TA

format:
  html:
    theme: cosmo
    toc: true